---
# tasks file for java-install
- name: Install OpenJDK 11
  apt:
    name: openjdk-11-jdk
    state: present
    update_cache: yes
  become: yes

- name: Install Maven
  apt:
    name: maven
    state: latest
    update_cache: yes
  become: yes
